name: portfolio-backend
services:
  postgres:
    image: postgres:14
    container_name: portfolio-postgres
    restart: always
    ports:
      - 8002:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'portfolio']
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_DB: portfolio-db
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio2025backend

  # redis:
  #   image: redis
  #   ports:
  #     - 6365:6379
  #   healthcheck:
  #     test: ['CMD', 'redis-cli', 'ping']
  #     interval: 10s
  #     timeout: 30s
  #     retries: 3
