export enum INJECTION_SERVICE_TOKEN {
  USER_SERVICE = 'USER_SERVICE',
  AUTH_SERVICE = 'AUTH_SERVICE',
  PORTFOLIO_SERVICE = 'PORTFOLIO_SERVICE',
  ACHIEVEMENT_SERVICE = 'ACHIEVEMENT_SERVICE',
  CONTACT_SERVICE = 'CONTACT_SERVICE',
  USER_SKILL_SERVICE = 'USER_SKILL_SERVICE',
  PROJECT_SERVICE = 'PROJECT_SERVICE',
  PROJECT_SKILL_SERVICE = 'PROJECT_SKILL_SERVICE',
}
